server:
  port: 8081

spring:
  application:
    name: employee
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: T3ch!shK3

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true